common:
  columns:
    - Job_Level
    - Years_at_Company
    - Monthly_Hours_Worked
    - Remote_Work
    - Meetings_per_Week
    - Tasks_Completed_Per_Day
    - Overtime_Hours_Per_Week
    - Work_Life_Balance
    - Job_Satisfaction
    - Productivity_Score
    - Absences_Per_Year
  target: productivity

preprocess:
  input: data/raw/data.csv
  output: data/processed
  artifact_path: artifacts/preprocessor.pkl



train :
  data_path: data/processed/train.csv
  model_path: models/model.pkl
  param_grid:
    n_estimators: [50, 100, 200, 300]
    max_depth: [null, 5, 10]
    min_samples_split: [2, 5, 10, 50]
    min_samples_leaf: [1, 2, 5, 20]

evaluate :
  data_path: data/processed/test.csv
  model_path: models/model.pkl
  